version: '3.8'
services:
  dynamodb-local:
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  aws-cli:
    depends_on:
      - dynamodb-local
    image: amazon/aws-cli
    container_name: aws-cli
    ports:
      - "8080:8080"
    environment:
      AWS_DEFAULT_PROFILE: dynamodb-local
      AWS_ENDPOINT: --endpoint-url=http://dynamodb-local:8000
    entrypoint: /bin/sh -c
    volumes:
      - './dynamodb-init-scripts:/dynamodb-init-scripts'
    command: >
      "
      sleep 5
        for script_name in /dynamodb-init-scripts/*.sh; do
          sh $$script_name
        done
      "